package com.auction.common.protocol;

public enum MessageType {
    PLACE_BID_REQ,
    PLACE_BID_RES,
    BID_UPDATED_EVENT,
    ERROR_RES,
    AUCTION_CLOSED_EVENT,
    LOGIN_REQ,
    LOGIN_RES,
    LIST_AUCTIONS_REQ,
    LIST_AUCTIONS_RES,
    REGISTER_REQ,
    REGISTER_RES,
    SUBSCRIBE_REQ,
    UNSUBSCRIBE_REQ,
    SUBMIT_LISTING_REQ,
    SUBMIT_LISTING_RES,
    ADMIN_ACTION_REQ,
    ADMIN_ACTION_RES,
    LIST_USERS_REQ,
    LIST_USERS_RES,
    UPDATE_USER_REQ,
    UPDATE_USER_RES
}